/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.spring.gradle.version;

import io.spring.gradle.version.order.SpringVersionLister;
import io.spring.gradle.version.status.RcStatusRule;
import org.gradle.api.Action;
import org.gradle.api.Plugin;
import org.gradle.api.Project;
import org.gradle.api.artifacts.dsl.ComponentMetadataHandler;
import org.gradle.api.artifacts.repositories.ArtifactRepository;
import org.gradle.api.artifacts.repositories.MetadataSupplierAware;

/**
 */
public class SpringDynamicVersionPluginPlugin implements Plugin<Project> {
    public void apply(Project project) {
        project.getDependencies().components(new Action<ComponentMetadataHandler>() {
            @Override
            public void execute(ComponentMetadataHandler handler) {
                handler.all(RcStatusRule.class);
            }
        });
        project.getRepositories().configureEach(new Action<ArtifactRepository>() {
            @Override
            public void execute(ArtifactRepository repository) {
                if (repository instanceof MetadataSupplierAware) {
                    ((MetadataSupplierAware) repository).setComponentVersionsLister(
                            SpringVersionLister.class);
                }
            }
        });
    }
}
